enabled: true

image:
  repository: ethereum/client-go
  tag: v1.9.23
  pullPolicy: IfNotPresent

network: goerli

datadir: /data

ports:
  rpc: 8545
  discovery: 30303
  metrics: 8580

# these will be merged with the above config values
args: [
  "--nousb",
  "--http",
  "--http.addr=0.0.0.0",
  "--metrics",
  "--metrics.addr=0.0.0.0",
  "--http.api=eth,net,web3,txpool",
  "--ws",
  "--ws.addr=0.0.0.0",
  "--syncmode=fast",
]

storage:
  className: aws-efs
  accessModes: [ "ReadWriteMany" ]
  capacity: 300Gi

servicemonitor:
  enabled: false

resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /metrics
    port: metrics
  initialDelaySeconds: 30
  failureThreshold: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /metrics
    port: metrics
  initialDelaySeconds: 30
  failureThreshold: 5
  periodSeconds: 10